topology: lattice
state_representation: S1234
n_agents: 400
k: 4
alpha: 0.05
epsilon: 0.05
gamma: 0.99
rho: 1
n_rounds: 40000
reward_window: 10
sample_every: 10
coop_n_divisions: 2
reward_n_divisions: 2
ws_beta: 0.1
seed: 478163327
